import { Suspense, lazy } from 'react'
import type { ReactNode } from 'react'
import { AppShell } from '../../components/AppShell/AppShell'
import { hasAmplifyBackend } from '../../services/amplify/client'
import styles from './AuthGate.module.css'

// Loaded only when a backend is configured, keeping the Amplify SDK out of the
// local-mode bundle entirely.
const AuthenticatedApp = lazy(() => import('./AuthenticatedApp'))

interface AuthGateProps {
  children: ReactNode
}

/**
 * Wraps the app in Cognito authentication when an Amplify backend is present
 * (`amplify_outputs.json` generated by the sandbox). Without a backend the app
 * renders in local-only mode, so frontend development never requires AWS.
 */
export function AuthGate({ children }: AuthGateProps) {
  if (!hasAmplifyBackend) {
    return (
      <AppShell
        headerActions={<span className={styles.badge}>Local mode</span>}
      >
        {children}
      </AppShell>
    )
  }

  return (
    <Suspense
      fallback={
        <AppShell>
          <p>Loading…</p>
        </AppShell>
      }
    >
      <AuthenticatedApp>{children}</AuthenticatedApp>
    </Suspense>
  )
}
